name: "prettier"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: "bash"

jobs:
  prettier:
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Node.js"
        uses: "actions/setup-node@v4"
        with:
          node-version: "22"

      - name: "Install dependencies"
        run: "npm install --no-save @prettier/plugin-xml"

      - name: "Run prettier"
        run: "npm exec --yes prettier -- --plugin=@prettier/plugin-xml --check ."
